import React from 'react';
import {
  Modal,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

type Props = { visible: boolean; onClose: () => void };

export default function HelpOverlay({ visible, onClose }: Props) {
  const insets = useSafeAreaInsets();
  return (
    <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
      <View style={styles.container}>
        {/* Backdrop — tapping it closes the modal */}
        <Pressable style={StyleSheet.absoluteFill} onPress={onClose} />

        {/* Card — sibling of backdrop, so ScrollView has no Pressable ancestor competing for touches */}
        <View style={[styles.card, { marginTop: insets.top + 40, marginBottom: insets.bottom + 40 }]}>
          <Text style={styles.title}>Mandelbrot Flight Simulator</Text>

          <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator>
            <Text style={styles.heading}>What is the Mandelbrot set?</Text>
            <Text style={styles.body}>
              {`Pick any point on the number plane — call it c. Now do this: start at zero, square it, add c, square the result, add c again, and keep going. For most points the numbers shoot off to infinity. But for some special points they stay bounded forever — those points form the Mandelbrot set, the black region you see on screen.

The boundary between "flies away" and "stays put" is where all the fractal detail lives. How quickly a point escapes to infinity determines its color — nearby escapes get one color, slower escapes get another, producing the rich gradient you see.

No matter how far you zoom in, new spirals, bulbs, and miniature copies of the whole set keep appearing. It never gets simpler or repeats exactly. The Mandelbrot set is infinite in complexity, generated by one of the simplest rules in mathematics: z → z² + c.`}
            </Text>

            <View style={styles.divider} />

            <Text style={styles.heading}>What is the Julia set?</Text>
            <Text style={styles.body}>
              {`The Julia set is a close cousin of the Mandelbrot set. Instead of asking "which starting values of c stay bounded?", you pick one fixed value of c and ask "which starting points z stay bounded when you repeatedly apply z → z² + c?"

The answer draws a completely different fractal for every value of c you choose. Move the crosshair to a point deep inside the Mandelbrot set and the Julia set is a solid, connected blob. Move it near the boundary and the Julia set explodes into intricate dust and tendrils. Move it outside and the Julia set shatters into disconnected points.

This is the heart of the app: every point in the Mandelbrot set is secretly a map to a Julia set. Navigating the Mandelbrot set is like flipping through an infinite catalog of Julia set artwork.`}
            </Text>

            <View style={styles.divider} />

            <Text style={styles.heading}>Inspiration credits</Text>
            <Text style={styles.body}>
              {'Ben Sparks · Holly Krieger · Damnimp · Tom Kerrigan · Benoit B. Mandelbrot · Gaston Julia'}
            </Text>
          </ScrollView>

          <Pressable style={styles.closeBtn} onPress={onClose}>
            <Text style={styles.closeText}>Close</Text>
          </Pressable>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  card: {
    backgroundColor: '#111',
    borderRadius: 16,
    padding: 24,
    height: '80%',
    flexDirection: 'column',
  },
  title: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
    textAlign: 'center',
  },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 8 },
  heading: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
    marginTop: 4,
  },
  body: {
    color: '#ccc',
    fontSize: 14,
    lineHeight: 22,
  },
  divider: {
    height: 1,
    backgroundColor: '#333',
    marginVertical: 20,
  },
  closeBtn: {
    marginTop: 20,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingVertical: 10,
    backgroundColor: '#333',
    borderRadius: 20,
  },
  closeText: { color: '#fff', fontSize: 15, fontWeight: '600' },
});
